name: ci/cd pipeline

on: 
  push:
    branches:
      - main
      - workbranch # Menjalankan pipeline di branch "workbranch" juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
        
      - name: Run tests
        run: go test -v ./... 
